# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 271f10cf0d770fe55f0b21e8c10714022580b851c4ace6df787b13e8f69343be23a3a3ce3a6db98bc6534f63bc5f22cb01aaa7b73f32dc880bc380d090b86462

test:
  secret_key_base: dc97d3133a3da03c046a4e4f10e7580b58c4573b20ee468164444f2428da478bafe0c7656bbbfa8c999bc24ce6d389116c0608e8eb68237732dc4ba1ccc2f877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
